-- 数据库表结构 SQL 语句
-- 生成时间: 03/23/2026 14:53:52

CREATE TABLE `announcement` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '公告ID',\n  `title` varchar(100) NOT NULL COMMENT '公告标题',\n  `content` text NOT NULL COMMENT '公告内容',\n  `type` tinyint DEFAULT '1' COMMENT '公告类型�?-系统公告�?-活动通知�?-维护通知',\n  `is_top` tinyint DEFAULT 0 COMMENT '是否置顶�?-否，1-�?,\n  `status` tinyint DEFAULT '1' COMMENT '状态：0-下架�?-上架',\n  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',\n  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除�?-未删除，1-已删�?,\n  PRIMARY KEY (`id`),\n  KEY `idx_type` (`type`),\n  KEY `idx_status` (`status`),\n  KEY `idx_is_top` (`is_top`),\n  KEY `idx_publish_time` (`publish_time`),\n  KEY `idx_announcement_status` (`status`),\n  KEY `idx_announcement_top` (`is_top`),\n  KEY `idx_announcement_publish` (`publish_time`)\n) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='公告�?
;

CREATE TABLE `comment_reply` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '回复ID',\n  `comment_id` bigint NOT NULL COMMENT '评论ID',\n  `user_id` bigint NOT NULL COMMENT '回复用户ID',\n  `parent_id` bigint DEFAULT 0 COMMENT '父回复ID�?表示直接回复评论�?,\n  `content` text NOT NULL COMMENT '回复内容',\n  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除�?-未删除，1-已删�?,\n  PRIMARY KEY (`id`),\n  KEY `idx_comment_id` (`comment_id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_parent_id` (`parent_id`),\n  KEY `idx_create_time` (`create_time`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='评论回复�?
;

CREATE TABLE `forum_post` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '帖子ID',\n  `title` varchar(100) NOT NULL COMMENT '帖子标题',\n  `content` text NOT NULL COMMENT '帖子内容',\n  `user_id` bigint NOT NULL COMMENT '发帖用户ID',\n  `scenic_id` bigint DEFAULT NULL COMMENT '关联景点ID（可选）',\n  `route_id` bigint DEFAULT NULL COMMENT '关联路线ID（可选）',\n  `view_count` int DEFAULT 0 COMMENT '浏览�?,\n  `reply_count` int DEFAULT 0 COMMENT '回复�?,\n  `is_top` tinyint DEFAULT 0 COMMENT '是否置顶�?-否，1-�?,\n  `is_essence` tinyint DEFAULT 0 COMMENT '是否精华�?-否，1-�?,\n  `is_audit` tinyint DEFAULT '1' COMMENT '审核状态：0-未审核，1-已通过�?-已拒�?,\n  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',\n  `audit_remark` varchar(200) DEFAULT NULL COMMENT '审核备注',\n  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除�?-未删除，1-已删�?,\n  PRIMARY KEY (`id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_scenic_id` (`scenic_id`),\n  KEY `idx_route_id` (`route_id`),\n  KEY `idx_is_top` (`is_top`),\n  KEY `idx_is_essence` (`is_essence`),\n  KEY `idx_is_audit` (`is_audit`),\n  KEY `idx_create_time` (`create_time`),\n  KEY `idx_forum_post_user` (`user_id`),\n  KEY `idx_forum_post_scenic` (`scenic_id`),\n  KEY `idx_forum_post_route` (`route_id`),\n  KEY `idx_forum_post_audit` (`is_audit`),\n  CONSTRAINT `fk_forum_post_route` FOREIGN KEY (`route_id`) REFERENCES `travel_route` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_forum_post_scenic` FOREIGN KEY (`scenic_id`) REFERENCES `scenic` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_forum_post_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='论坛帖子�?
;

CREATE TABLE `forum_reply` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '回复ID',\n  `post_id` bigint NOT NULL COMMENT '帖子ID',\n  `user_id` bigint NOT NULL COMMENT '回复用户ID',\n  `parent_id` bigint DEFAULT NULL COMMENT '父回复ID，NULL表示为顶级回�?,\n  `content` text NOT NULL COMMENT '回复内容',\n  `is_audit` tinyint DEFAULT '1' COMMENT '审核状态：0-未审核，1-已通过�?-已拒�?,\n  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',\n  `audit_remark` varchar(200) DEFAULT NULL COMMENT '审核备注',\n  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除�?-未删除，1-已删�?,\n  PRIMARY KEY (`id`),\n  KEY `idx_post_id` (`post_id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_parent_id` (`parent_id`),\n  KEY `idx_is_audit` (`is_audit`),\n  KEY `idx_create_time` (`create_time`),\n  KEY `idx_forum_reply_post` (`post_id`),\n  KEY `idx_forum_reply_user` (`user_id`),\n  KEY `idx_forum_reply_parent` (`parent_id`),\n  KEY `idx_forum_reply_audit` (`is_audit`),\n  CONSTRAINT `fk_forum_reply_parent` FOREIGN KEY (`parent_id`) REFERENCES `forum_reply` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_forum_reply_post` FOREIGN KEY (`post_id`) REFERENCES `forum_post` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_forum_reply_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='论坛回复�?
;

CREATE TABLE `route_category` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类ID',\n  `name` varchar(50) NOT NULL COMMENT '分类名称',\n  `description` varchar(200) DEFAULT NULL COMMENT '分类描述',\n  `sort` int DEFAULT 0 COMMENT '排序�?,\n  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  PRIMARY KEY (`id`),\n  KEY `idx_sort` (`sort`)\n) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='路线分类�?
;

CREATE TABLE `route_scenic_relation` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关联ID',\n  `route_id` bigint NOT NULL COMMENT '路线ID',\n  `scenic_id` bigint NOT NULL COMMENT '景点ID',\n  `day_number` int NOT NULL COMMENT '第几天（1-based�?,\n  `sort_order` int DEFAULT 0 COMMENT '当天内排�?,\n  `description` text COMMENT '景点说明/推荐理由',\n  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_route_scenic_day` (`route_id`,`scenic_id`,`day_number`),\n  KEY `idx_route_id` (`route_id`),\n  KEY `idx_scenic_id` (`scenic_id`),\n  KEY `idx_route_scenic_route` (`route_id`,`scenic_id`),\n  CONSTRAINT `fk_route_scenic_route` FOREIGN KEY (`route_id`) REFERENCES `travel_route` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `fk_route_scenic_scenic` FOREIGN KEY (`scenic_id`) REFERENCES `scenic` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='路线-景点关联�?
;

CREATE TABLE `scenic` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '景点ID',\n  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '景点名称',\n  `description` text COLLATE utf8mb4_unicode_ci COMMENT '官方介绍',\n  `images` text COLLATE utf8mb4_unicode_ci COMMENT '图片URL（多个用逗号分隔�?,\n  `price` decimal(10,2) DEFAULT 0.00	 COMMENT '价格',\n  `score` decimal(3,2) NOT NULL DEFAULT 0.00	 COMMENT '评分�?-5�?,\n  `location` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '地点',\n  `view_count` int NOT NULL DEFAULT 0 COMMENT '浏览�?,\n  `category_id` bigint NOT NULL COMMENT '关联分类ID',\n  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-下架�?-上架',\n  `recommend_level` tinyint DEFAULT 0 COMMENT '推荐等级�?-普通，1-推荐�?-热门�?-必游',\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除 0-未删�?1-已删�?,\n  PRIMARY KEY (`id`),\n  KEY `idx_category_id` (`category_id`),\n  KEY `idx_location` (`location`),\n  KEY `idx_score` (`score`),\n  KEY `idx_view_count` (`view_count`),\n  KEY `idx_status` (`status`)\n) ENGINE=InnoDB AUTO_INCREMENT=75 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='景点�?
;

CREATE TABLE `scenic_category` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类ID',\n  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '分类名称：自然风�?人文历史/主题乐园',\n  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `description` text COLLATE utf8mb4_unicode_ci COMMENT 'description',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_name` (`name`)\n) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='景点分类�?
;

CREATE TABLE `scenic_tag` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '标签ID',\n  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标签名称：如适合亲子、网红打�?,\n  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_name` (`name`)\n) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='景点标签�?
;

CREATE TABLE `scenic_tag_relation` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关联ID',\n  `scenic_id` bigint NOT NULL COMMENT '景点ID',\n  `tag_id` bigint NOT NULL COMMENT '标签ID',\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_scenic_tag` (`scenic_id`,`tag_id`),\n  KEY `idx_scenic_id` (`scenic_id`),\n  KEY `idx_tag_id` (`tag_id`)\n) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='景点-标签关联�?
;

CREATE TABLE `travel_route` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '路线ID',\n  `name` varchar(100) NOT NULL COMMENT '路线名称',\n  `description` text COMMENT '路线描述',\n  `category_id` bigint DEFAULT NULL COMMENT '路线分类ID',\n  `budget` decimal(10,2) DEFAULT 0.00	 COMMENT '预算估算（元�?,\n  `duration_days` int DEFAULT '1' COMMENT '行程天数',\n  `best_season` varchar(50) DEFAULT NULL COMMENT '最佳季节，如：春季,夏季,秋季,冬季',\n  `images` json DEFAULT NULL COMMENT '路线图片URL数组',\n  `status` tinyint DEFAULT '1' COMMENT '状态：0-下架,1-上架',\n  `view_count` int DEFAULT 0 COMMENT '浏览�?,\n  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0 COMMENT '逻辑删除�?-未删�?1-已删�?,\n  PRIMARY KEY (`id`),\n  KEY `idx_category_id` (`category_id`),\n  KEY `idx_status` (`status`),\n  KEY `idx_view_count` (`view_count`),\n  KEY `idx_create_time` (`create_time`),\n  KEY `idx_route_category` (`category_id`),\n  KEY `idx_route_status` (`status`),\n  KEY `idx_route_view_count` (`view_count`),\n  KEY `idx_route_create_time` (`create_time`)\n) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='旅游路线�?
;

CREATE TABLE `user` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID',\n  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户名（唯一�?,\n  `password` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '密码（BCrypt加密�?,\n  `nickname` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '昵称',\n  `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '头像URL',\n  `role` tinyint NOT NULL DEFAULT 0 COMMENT '角色�?-普通用户，1-管理�?,\n  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：0-禁用�?-正常',\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_username` (`username`),\n  KEY `idx_role` (`role`),\n  KEY `idx_status` (`status`)\n) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户�?
;

CREATE TABLE `user_collection` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '收藏ID',\n  `user_id` bigint NOT NULL COMMENT '用户ID',\n  `remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注（管理端可填�?,\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '收藏时间',\n  `deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除�?-未删除，1-已删除）',\n  `type` int DEFAULT '1' COMMENT '收藏类型�?-景点�?-路线',\n  `target_id` bigint DEFAULT NULL COMMENT '目标ID（景点ID或路线ID�?,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_user_type_target` (`user_id`,`type`,`target_id`),\n  UNIQUE KEY `uk_user_target` (`user_id`,`type`,`target_id`),\n  UNIQUE KEY `uk_collection_user_target` (`user_id`,`type`,`target_id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `fk_user_collection_scenic` (`target_id`),\n  CONSTRAINT `fk_user_collection_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户收藏�?
;

CREATE TABLE `user_comment` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '评论ID',\n  `user_id` bigint NOT NULL COMMENT '用户ID',\n  `content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '评论内容',\n  `is_audit` tinyint NOT NULL DEFAULT '1' COMMENT '是否审核�?-未审核，1-已通过（测试版默认1�?,\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',\n  `deleted` tinyint(1) DEFAULT 0 COMMENT '逻辑删除�?-未删除，1-已删除）',\n  `type` int DEFAULT '1' COMMENT '评论类型�?-景点�?-路线',\n  `target_id` bigint DEFAULT NULL COMMENT '目标ID（景点ID或路线ID�?,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_comment_user_target` (`user_id`,`type`,`target_id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_is_audit` (`is_audit`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户评论�?
;

CREATE TABLE `user_preference` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '偏好ID',\n  `user_id` bigint NOT NULL COMMENT '用户ID',\n  `category_id` bigint DEFAULT NULL COMMENT '偏好分类ID（可空）',\n  `tag_id` bigint DEFAULT NULL COMMENT '偏好标签ID（可空）',\n  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',\n  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',\n  `deleted` tinyint DEFAULT 0,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_user_category_tag` (`user_id`,`category_id`,`tag_id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_category_id` (`category_id`),\n  KEY `idx_tag_id` (`tag_id`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户偏好�?
;

CREATE TABLE `view_record` (\n  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '浏览记录ID',\n  `user_id` bigint NOT NULL COMMENT '用户ID',\n  `scenic_id` bigint NOT NULL COMMENT '景点ID',\n  `view_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '浏览时间',\n  `deleted` tinyint DEFAULT 0,\n  PRIMARY KEY (`id`),\n  KEY `idx_user_id` (`user_id`),\n  KEY `idx_scenic_id` (`scenic_id`),\n  KEY `idx_view_time` (`view_time`)\n) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='浏览记录�?
;

